#!/usr/bin/env sh
. "envy.sh"

envd "$@"

cat > envy <<-EOT
	#!/usr/bin/env sh
	EOT

if [ "${ENVX-o}" = "${ENVX-x}" ]; then
	mkdir -p -- "${ENVX}"
	ENVO="$(dirname -- "${0}")"
	cp -H -- "${ENVO}/envy.sh" "${ENVO}/env.sh" "${ENVX}"
	cat >> envy <<-EOT
		export PATH="$(realpath -- "${ENVX}"):\${PATH}"
		EOT
fi

cat >> envy <<-EOT
	. "envy.sh"
	case "\$(command -v -- envy)" in
		(/*) type envy;;
		(*) envy "\$@";;
	esac
	EOT

chmod -- +x envy

cat > env.sh <<-EOT
	. "env.sh"
	EOT
