#!/usr/bin/env sh
. "envy.sh"

envd "$@"

if [ ! -e "env.sh" ]; then
	cat > env.sh <<-EOT
		. "env.sh"
		EOT
fi

if [ ! -e "envy" ]; then
	cat > envy <<-EOT
		#!/usr/bin/env sh
		EOT

	if [ "${ENVX-o}" = "${ENVX-x}" ]; then
		ENVO="$(dirname -- "${0}")"
		mkdir -p -- "${ENVX}"
		cp -H -- "${ENVO}/envy.sh" "${ENVO}/env.sh" "${ENVX}"
		ENVX="$(realpath -- "${ENVX}")"
		ENVX="${ENVX#"$(pwd -P)/"}"
		cat >> envy <<-EOT
			export PATH="\$(realpath -- "\$(dirname -- "\${0}")/${ENVX}"):\${PATH}"
			EOT
	fi

	cat >> envy <<-EOT
		. "envy.sh"
		case "\$(command -v -- envy)" in
			(/*) type envy;;
			(*) envy "\$@";;
		esac
		EOT

	chmod -- +x envy
fi
