#!/usr/bin/env sh

ENVY="$(realpath -- "${0}")"
: ${ENVYSH="$(dirname -- "${ENVY}")/envy.sh"}
ENVYSH="$(realpath -- "${ENVYSH}")"
: ${ENVSH="$(dirname -- "${ENVY}")/env.sh"}
ENVSH="$(realpath -- "${ENVSH}")"
: ${ENVS=""}

ENVSTAIL=$#
ENVSARGS="$*"

getenvs () {
	while [ $# -gt 0 ]; do
		if [ "${1}" = "--" ]; then
			ENVSTAIL=$#
			shift
			ENVSARGS="$*"
		else
			shift
		fi
	done

	set -- ${ENVSARGS}

	if [ $# -eq 0 ]; then
		if [ "${ENV-o}" = "${ENV-x}" ]; then
			set -- "."
		fi
	fi

	ENVSSPIN=$#
	while [ ${ENVSSPIN} -gt 0 ]; do
		set -- "$@" "$(realpath "${1}")"
		shift
		ENVSSPIN=$((ENVSSPIN-1))
	done

	set -- ${ENVS} "$@"
	ENVS="$*"
}

if [ "${IFS-o}" = "${IFS-x}" ]; then
	getenvs "$@"
else
	IFS=":"
	getenvs "$@"
	unset IFS
fi

ENVSSPIN=$(($#-ENVSTAIL))
while [ ${ENVSSPIN} -gt 0 ]; do
	set -- "$@" "${1}"
	shift
	ENVSSPIN=$((ENVSSPIN-1))
done
unset ENVSSPIN

shift ${ENVSTAIL}

: ${ENV="${ENVSH}"}
ENV="$(realpath -- "${ENV}")"

export ENVY
export ENVYSH
export ENVSH
export ENVS
export ENV

# POSIX User Portability Utilities sh
exec sh "$@"
