#!/usr/bin/env sh

ENVY=$(
	ABSENVY="${PWD%"/"}/${0#"/"}"
	cd $(dirname -- "${ABSENVY}")
	cat <<-EOT
		${PWD}/$(basename -- "${ABSENVY}")
		EOT
	)
: ${ENV="env.sh"}
: ${ENVS=""}
: ${ENVYSH="${ENVY}.sh"}

TAIL=0
ENVSARGS=""

getenvs () {
	ENVSARGS="$*"
	while [ $# -gt 0 ]; do
		if [ $1 = "--" ]; then
			TAIL=$#
			shift
			ENVSARGS="$*"
		else
			shift
		fi
	done
	set -- ${ENVS} ${ENVSARGS}
	ENVS="$*"
}

if [ "${IFS-o}" = "${IFS-x}" ]; then
	getenvs
else
	IFS=":"
	getenvs
	unset IFS
fi

SPIN=${TAIL}

while [ ${SPIN} -gt 0 ]; do
	HEAD="${1}"
	shift
	set -- "$@" "${HEAD}"
	SPIN=$((SPIN-1))
done

shift $TAIL

export ENVY
export ENV
export ENVS
export ENVYSH
# POSIX User Portability Utilities sh
exec sh "${@}"
